### ISSUE TITLE
roadmapping

### ISSUE THREAD

**Issue by serapath** [playproject-io/datdot-chain#1]
## `@todo`
* [ ] transition chain code from datdot-service repo into this repo
* [ ] implement datdot-chain module as a replacement for polkadotjs and allow switching between
  * [ ] [`datdot-node-rust#1` roadmapping](https://github.com/playproject-io/datdot-node-rust/issues/1)
  * [ ] [`datdot-node-javascript#1` roadmapping](https://github.com/playproject-io/datdot-node-javascript/issues/1)

---
